name: protein_model
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu116
    - numpy==2.1.1
    - ipykernel==6.29.5
    - matplotlib==3.9.2
    - tqdm==4.66.5